### ISSUE TITLE
Example notebooks for training and inference

### ISSUE THREAD

**Issue by josephrocca** [deepmind/hierarchical_perceiver#1]
Hey @skoppula, I was going to ask on that other issue/thread, but figured here is better: The readme mentions that a Colab for inference is on the way, but I was wondering if there's a rough ETA? A simple training notebook would be great too if possible!

No worries if there's no ETA currently. I'll leave this issue open to track this addition.

**Comment by skoppula** [comment]
Hey! Yes, putting together this inference Colab is on our to-do list because I think it would make the lives of people building on or comparing against the work a lot easier. Is there a specific checkpoint you were looking for that you'd want us to prioritize (the segmentation finetuned one? The MAE pre-training base checkpoint? ImageNet supervised?)?

To be completely realistic: (1) this release is low on the team's priorities right now, with most of us working on other work, but I do hope to get free time within the next couple weeks to fish out that checkpoint and extract out the weights in a Colab-friendly way. (2) I don't have plans to merge in of the training code, which is much more involved to release and would require quite a few more approvals, so unfortunately, I can say with high likelihood we won't have the bandwidth to put that out. But if you have specific questions about training procedures, feel free to reach out to Joao or any of us, and we'd be happy to answer.

Yes, please feel free to leave to leave this issue open until we get around to putting out a Colab!

**Comment by josephrocca** [comment]
Ahh, I see - I was actually mainly interested in the training side of things, and hoping that there'd be a simple example notebook to get up and running like there was with the PerceiverAR repo. It's a shame if it's unlikely this repo will get that, but either way, I really  appreciate the work you've put into getting the current code released!

**Comment by skoppula** [comment]
Hello -- closing this, as we won't get around to this sadly 😔. I don't think we'll get around to releasing a sanitized, external-ready training setup in a time horizon that might be useful for you, and it's currently not a team priority at the moment.
